### ISSUE TITLE
memorial day AOTD 

### ISSUE THREAD

**Issue by oobondes** [ArchaicBubba/ArmyKnowledgeOffline#1]
hey, I found a small issue with your main.js at line 523-537

`if (m == 4) { // Asian American Pacific Islander Heritage Month`
`    AOTD = "It is currently Asian American Pacific Islander Heritage Month";`
`  } else if (m == 4 && d == 30) { // Memorial Day` <-- this line won't ever be reached due to the if statement before it
`    AOTD = "It is currently Memorial Day";`
`  }`

you could swap the order of the two if statements and fix it, or use a nested if statement

`if (m == 4) {`
`    if (d==30){//memorial day`
`         AOTD = "It is currently Memorial Day";`
`    else{// Asian American Pacific Islander Heritage Month`
`        AOTD = "It is currently Asian American Pacific Islander Heritage Month";`
`}`

Also, awesome work on setting this site up for everyone when AKO disappeared overnight!

**Comment by ArchaicBubba** [comment]
Code has been fixed to read
else if (m == 4 && d != 30) { // Asian American Pacific Islander Heritage Month 
AOTD = "It is currently Asian American Pacific Islander Heritage Month";
} 
The if statement will no longer trigger on the 30th of the month.
Thanks for the heads up.
