### ISSUE TITLE
Allow favorites

### ISSUE THREAD

**Issue by kaush520** [ArchaicBubba/ArmyKnowledgeOffline#11]
If possible, allow creating favorites that can go to the top of the page. No profile creation, but ordering of the pages based on data stored in cookies. As an example, I access Email, MyPay, iPerms and Teams for the most part. I find Email, iPerms and MyPay on the home page but have to go to all links to find Teams.

Others may have their own regular favorites. A feature like this would be awesome. 

Thanks for building this

**Comment by ArchaicBubba** [comment]
Hello, Custom quick links is already present in the current site. There is no account creation and user data is stored in local storage so it doesn't go back to a server like a cookie would. go to https://akoffline.us/SiteSettings.html > "Custom Quicklinks Settings". Here you can drag and drop the likes you want to use into the spots you want to use them in. Make sure you click save before you leave the page so they take effect. Additionally if you want to set it once and not again you can export your settings, so you can import them on another computer or different browser.

**Comment by kaush520** [comment]
This is awesome, I didn't know. Thanks so much!
______________

Be Creative, Stay Connected, Keep Inventing!

Best,
Kaush Kumar
