### ISSUE TITLE
ERB/ORB National Guard

### ISSUE THREAD

**Issue by mgiduck13** [ArchaicBubba/ArmyKnowledgeOffline#12]
The link on the tile labeled "MY ENLISTED/OFFICER RECORD BRIEF (NATIONAL GUARD)" nested underneath the "SOLDIER RECORD BRIEF (FOLDER)" tile brings you to a bit if an ambiguous link to the ERB/ORB. You can access it through the current link by selecting "Self Service" midway down, and then click the ERB link on the following page. A more direct URL to the National Guard ERB is: https://arngg1.ngb.army.mil/v3/SelfService/Careercenter/RBMain.aspx

**Comment by ArchaicBubba** [comment]
To ensure I am read your issue correctly, The SRB Card for National Guard's link is incorrect (or mostly so) and the link provided above is better/more direct?

**Comment by mgiduck13** [comment]
That is correct. Please ops test it before letting it rip in case that is just how the links are working for me.
Sent from Yahoo Mail on Android 
 
  On Fri, Feb 24, 2023 at 15:18, ***@***.***> wrote:   


To ensure I am read your issue correctly, The SRB Card for National Guard's link is incorrect (or mostly so) and the link provided above is better/more direct?

**Comment by ArchaicBubba** [comment]
Link Verified, Will include in next update.
