### ISSUE TITLE
U.S. Armed Forces Legal Aid Email Not Found

### ISSUE THREAD

**Issue by cutsyfart** [ArchaicBubba/ArmyKnowledgeOffline#13]
I tried to apply for legal aid, but the link for Fort Irwin does not work and the email given to report updates needed for those links was not found. I'm going to try the other emails and see if they know, but....yeah. Deadend.

**Comment by ArchaicBubba** [comment]
I'm sorry, which link are you referring too?
Fort Irwins legal services contact info:
Phone: 760-380-5321/2307
Email: usarmy.irwin.imcom.mbx.ntc-osja-client-services@mail.mil
**Note email may have changed to usarmy.irwin.imcom.mbx.ntc-osja-client-services@army.mil
This is from https://home.army.mil/irwin/index.php/my-fort/all-services/legal-services
