### ISSUE TITLE
MEDPROS Tile

### ISSUE THREAD

**Issue by Pongo88** [ArchaicBubba/ArmyKnowledgeOffline#14]
The MEDPROs tile link wont work anymore. Some reason when i tloads its some very off the wall URL that lets you hit the first two log ins and then its a server issue. 

Think it needs updated to:

https://medpros.mods.army.mil/portal

**Comment by ArchaicBubba** [comment]
That is the link currently listed on the card. if you hover over the tile it will display the link in which you are clicking on in the bottom right/left corner of your screen. There might have been a site issue.
