### ISSUE TITLE
Teams login error 

### ISSUE THREAD

**Issue by kiantesmith1995** [ArchaicBubba/ArmyKnowledgeOffline#15]
I'm having issues logging into teams. I get an error message each time.

**Comment by ArchaicBubba** [comment]
This appears to be a conflict with the Microsoft's domain hint URI logic and the DoD teams. If for some odd reason you want to read about Microsoft's domain hints here is a [link](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/home-realm-discovery-policy). However if you wish to remain sane; know that the link has been updated site wide to "https://dod.teams.microsoft.us/". It should be updated in an hour or so. 
If the link still sends you to the old link with the domain hint URI, please clear your browsers cache for Army Knowledge Offline. This may or may not clear any custom settings that you have set. So I recommend that you export any saved settings on the site settings page first (if you have changed them). If dark mode is turned on, just click the dark mode button next to the search bar after resetting the cache. As dark mode isn't exported along with other site settings.
