### ISSUE TITLE
ATIS link broken

### ISSUE THREAD

**Issue by ajia117** [ArchaicBubba/ArmyKnowledgeOffline#17]
Army Training Information System (ATIS) link doesn't populate after login -- check link. Also, ATIS not searchable. 

EDIT: ~~[live link](https://atis.army.mil/)~~ link is to program site, live link to [learning](https://learn.atis.army.mil/)

**Comment by ArchaicBubba** [comment]
Fixed. Should now link to https://learn.atis.army.mil and be searchable with the acronym 'ATIS'.
