### ISSUE TITLE
My clothing record

### ISSUE THREAD

**Issue by Bleich23** [ArchaicBubba/ArmyKnowledgeOffline#3]
This is the only link that is not working.

**Comment by ArchaicBubba** [comment]
I will not be able to check or fix them until wendsday the 15th as I am out of town without a computer. Once I am back I will check, verify and fix the link as applicable.

**Comment by ArchaicBubba** [comment]
I was able to verify that the My clothing Record link was functioning today (2022-06-15) on a Non-DOD network using FireFox, Edge and Chrome. What browser are you using? Have you tried clearing your cookies for said browser?

**Comment by ArchaicBubba** [comment]
Seeing no response, I am assuming that the issue was rectified on the users end. This ticket will be closed
