### ISSUE TITLE
ERB card not working 

### ISSUE THREAD

**Issue by SPCBazile** [ArchaicBubba/ArmyKnowledgeOffline#4]
not just the erb card but there are a few card that every time i try and access them i get the same error. that say it cant reach the site on both microsoft edge and google chrome.

**Comment by ArchaicBubba** [comment]
Which cards besides ERB are not working correctly? Are you trying to access your ERB on a gov network? I will not be able to check or fix them until wendsday the 15th as I am out of town without a computer.

**Comment by keejohnny** [comment]
I see that they made it only accessible to a government network only.

**Comment by ArchaicBubba** [comment]
Closed due to lack of comment from original poster.
