### ISSUE TITLE
[Suggestion] Citi Commercial Cards

### ISSUE THREAD

**Issue by TwilightForge60** [ArchaicBubba/ArmyKnowledgeOffline#6]
https://home.cards.citidirect.com/CommercialCard/login

The above URL is to Citi Commercial Cards where Soldiers can log in to see the balance and make payments to their Government Travel Credit Card (GTCC).

**Comment by ArchaicBubba** [comment]
Thank you for the suggestion. Link in progress.

**Comment by ArchaicBubba** [comment]
Card has been added in current Site revision. Should go live in a day or so.
