### ISSUE TITLE
mail.mil only on DoD Network

### ISSUE THREAD

**Issue by thenrmldude** [ArchaicBubba/ArmyKnowledgeOffline#8]
From what I've gathered and done myself, the only way for those with a mail.mil to login (E4 and below) have to do so on a DoD network.

**Comment by ArchaicBubba** [comment]
Thank you for the heads up, I will look into it and change it on the site accordingly

**Comment by dkontyko** [comment]
I can shed some insight on this. Legacy web.mail.mil (DEE) is gone as of now. The mail.mil domain is still used by DISA, but it's for their Microsoft 365 tenant. 

For email, you should probably have two links: https://webmail.apps.mil for Army 365 and https://www.google.com/a/usa.army.mil for Army Google Workspace. As for how you tell which one you have: aside from asking your IMO, try logging in to both of them and see which one you're able to access.

**Comment by ArchaicBubba** [comment]
Thank you, I will add the above link to the site in the upcoming update.
